version: 0.0
os: linux
files:
  - source: index.php
    destination: /var/www/html/
  - source: img
    destination: /var/www/html/img/
hooks:
  BeforeInstall:
    - location: script/clean.sh
      runas: root
